### ISSUE TITLE
Plugin documenentation

### ISSUE THREAD

**Issue by wazari972** [ludovicchabant/PieCrust2#15]
Hello,

I'm working on a website generator for my dive logs (http://git.0x972.info/subsurface2jinja.git/tree/), that I developed with PieCrust concepts in mind. Now I see that v2 is based on Python, and I think that my tool could benefit from PieCrust engine, so I'm wondering if I could adapt my subsurface2jinja into a Piecrust plugin. You can take a look at http://plongee.0x972.info for the result.

Is there any documentation for writing such plugins ? I already connected a __piecrust_plugin__ class to Piecrust, but I'm not sure how to implement the class get* methods should return.

Thanks for your help

**Comment by ludovicchabant** [comment]
Yeah the documentation is a bit "light" at the moment. If I understand correctly, you've followed the explanations from the [official docs](http://bolt80.com/piecrust/en/latest/code/) and now you're wondering what to do with your subclass of `PieCrustPlugin`? You can look at the built-in plugin for inspiration (see `piecrust.plugins.builtin`).

Well it really depends on what you want to do, so you'd have to explain your use-case in more detail.... but I imagine you have a bunch of information somewhere about your dives, and you want to generate content for each?

In that case what you're probably looking for is `getSources`. It lets you return any custom _page sources_ that your plugin may define. You could make a page source that returns one page for each dive, or something like that. It could procedurally generate page metadata (header, title, etc.) based on whatever info you have per-dive. Depending on how the dive data look like, there may be some work required to properly abstract page sources and page factories away from the common case of one text file per page (it's supposed to not assume that it's the case, but I know there are a few shortcuts in the code...).

**Comment by wazari972** [comment]
alright, so I'll dig into the source code ! if I manage to build everything
I want, I'll try to write a bit of explanation on how it works

currently I've been able to list different "posts" in my Source plugin, but
I'm not sure yet where I the transformation from the FS file to the object
provided to jinja is done ...

To simplify what I want to do, it's putting my blog posts into a single XML
file (with additional processing, like generating graphs and resizing
images), and generate my blog from entries of this XML file.

**Comment by ludovicchabant** [comment]
A page's contents are parsed [here](https://github.com/ludovicchabant/PieCrust2/blob/master/piecrust/page.py#L282) into "segment", i.e. bits of texts associated with a given format (markdown, textile, etc.). Then [over here](https://github.com/ludovicchabant/PieCrust2/blob/master/piecrust/rendering.py#L294) it gets passed to the template engine (Jinja2, etc.) and then to the formatter.

**Comment by ludovicchabant** [comment]
I started writing the API documentation so I'll close that now.
