### ISSUE TITLE
{{ piecrust.debug_info|safe }} not working

### ISSUE THREAD

**Issue by zimmicz** [ludovicchabant/PieCrust2#17]
Putting debug_info into the code results in this error with the latest code:

![screenshot from 2015-05-16 20 01 41](https://cloud.githubusercontent.com/assets/6543598/7667402/6eab845a-fc06-11e4-99e7-be991337c81d.png)

**Comment by ludovicchabant** [comment]
Woops, this was supposed to be an assert only when testing. I removed it with c1d33a73ce92cee338d3be9472aa5e5c1938a65e.  I also spent some time writing the infrastructure code to add unit tests for the preview server (acf120fbd8f5d542684a7a3540f1b5544a90b57c). Thanks!
