### ISSUE TITLE
Docs link to wrong CSS file

### ISSUE THREAD

**Issue by sinistersnare** [ludovicchabant/PieCrust2#22]
Hey, I am going through the documentation trying to get started with a website, and am on "Part 3: Adding colours", where we create some css using less.

The docs state that we link to the CSS with the following HTML:

`<link rel="stylesheet" type="text/css" href="/piecrust/en/latest/myblog.css"/>`

It seems the hyperlink is incorrect, as the path should be `/myblog.css` not `/piecrust/en/latest/myblog.css`.

Ahh, now that I look into the source code, it seems like you need to escape your `{{ site.root }}` with `{% raw %}` so it renders it as `{{ site.root }}`

**Comment by ludovicchabant** [comment]
Ah yes indeed, thanks for spotting that :)

**Comment by ludovicchabant** [comment]
Fixed with 895817344943f912d4c0d41190187e9cf85b4002.
