### ISSUE TITLE
Pagination - nex/prev page - tag pages

### ISSUE THREAD

**Issue by magarciaguerra** [ludovicchabant/PieCrust2#23]
Hi, again, Ludo :)

I found some new bugs. 

First:

I have an strange error with new post/older posts in index, when I click in older posts in order to watch page 2 of the blog, I get an error because piecrust baked this wrong url.

![issue601](https://cloud.githubusercontent.com/assets/4279626/9244102/4cb8e702-4198-11e5-9c98-1eb7d9950918.gif)

I have this code in template: 

![issue602](https://cloud.githubusercontent.com/assets/4279626/9244108/5a82896a-4198-11e5-91ce-32617f1bd284.gif)

And.. related to this, It doesn't work with tags because piecrust bakes a url like

![issue603](https://cloud.githubusercontent.com/assets/4279626/9244125/90be1a3a-4198-11e5-97c7-2c053e60adaa.gif)

It doesn't have first part of url, in this case: http://www.magarciaguerra.com/

But, this is also another thing that brings new problems with special characters. In Piecrust 1, tags with 'á', 'é' or 'ñ' were simplified, for example:

'informática' >>> 'informatica' (without 'á')

In piecrust2, piecrust bakes special characters and all the internal links are a mess, also, navigation links have this new url with, for example, "%25c3%25..."

Could we have again those simplified names for tags?

Thanks for all, I hope this helps ;)

**Comment by magarciaguerra** [comment]
Update:

I've solved one  of the issues: I've changed 
<a href="{{ pcurl(pagination.next_page) }}
deleting 'pcurl'
All seems works fine in pagination at index and at tag pagination :)

But I would like to have the option of change the special characters to normal characters in urls
Do you think if it is possible?
:-)

**Comment by ludovicchabant** [comment]
Ah yes, sorry, that's one last thing I broke from PieCrust v1. Fixed with b80280256a91e7f07f1b14781cd5aee06f8bd1d5.

You can update to the latest code from Github (I haven't pushed it to Pypi yet) and set `site/slugify_mode` [site configuration setting](http://bolt80.com/piecrust/en/latest/docs/reference/website-configuration/) to `lowercase,transliterate` to do what you want.
