### ISSUE TITLE
Assets not processed

### ISSUE THREAD

**Issue by alfetopito** [ludovicchabant/PieCrust2#25]
Hey there,

I'm following the tutorial and the beginning of the third part is failing:

```
$ chef serve
 * Running on http://localhost:8080/ (Press CTRL+C to quit)
Errors found in assets/myblog.less:
  [Errno 2] No such file or directory: '/home/alfeto/work/aikoo/piecrust/bla.bla/assets/myblog.less_9713fecd8a38a0615d45a1302332d809.map' -> '/home/alfeto/work/aikoo/piecrust/bla.bla/_cache/server_c21f969b5f03d33d43e04f8f136e7682/proc/less/myblog.less_9713fecd8a38a0615d45a1302332d809.map'
[   130.1 ms] processed 0 assets.
```

Using Python 3.4.3 and PieCrust==2.0.0b3

**Comment by alfetopito** [comment]
By the way, here is the log from `$ chef serve`
http://dpaste.com/0XQQM2Y.txt

**Comment by ludovicchabant** [comment]
Ah, very interesting... so I don't know if this has always been the case but it looks like `lessc` won't output anything if the input file is empty, or has all empty rules... which is why PieCrust can't find the output map file. You can safely ignore the error and continue with pasting the CSS code and it should catch it.

Thanks for reporting though! And while trying to repro, I ran into 2 other bugs :(   I guess I know what I'll be doing this week-end when I have free time :)

**Comment by alfetopito** [comment]
You are welcome, and I'm sorry hehe.

    Anyway, even after filling up the .less file I get the error.
    Couldn't it be that the base map file isn't being created?
    I'm not familiar with lessc, so I'm not sure what should be the expected output. Tried to look through https://github.com/ludovicchabant/PieCrust2/blob/master/piecrust%2Fprocessing%2Fless.py but I am of no help here.

Never mind the above paragraph, I left it there for reference of my own mistake.

Just tried a little harder and guess I know what the problem is.
I have no previous frontend experience, so I wasn't aware I had to have lessc installed when I begun (didn't find that mentioned in the tutorial), thus when I figured out it was needed, I apt-get installed it.
This time I tried to install it the proper way, using npm.
Now less is installed locally and I pointed to it on the config file:

```
less:
  bin: node_modules/.bin/lessc
```

And when I serve, I get no errors.

So that's it. The error was happening because I was using a system package manager's version which probably is very outdated.

I would just suggest you add a side note in the tutorial regarding given requirement, because another clueless person (like me =P) might also not be aware lessc should be installed.

**Comment by ludovicchabant** [comment]
Yeah the tutorial is not very complete in that regard. Maybe I'll change it to use a normal CSS file instead of a LessCSS one (so there's no need to install something).

**Comment by ludovicchabant** [comment]
FYI I changed the tutorial to use standard CSS so people don't need to install Less if they don't have it. I also fixed the bug where an previously non-existing `assets` folder wasn't detected if you create it while `chef serve` is running. Now it will pick it up if it appears. And last, if `config.yml` changes, the background pipeline will also reload it.
