### ISSUE TITLE
How to handle pages with "more" link

### ISSUE THREAD

**Issue by kinow** [ludovicchabant/PieCrust2#27]
Hi!

I'm migrating an old web site, that was built with the PHP Piecrust site generator. Some posts have the  tag, that worked as a flag to tell Piecrust to display the portion before it as an excerpt when paginating posts.

It seems to be still working, however, I couldn't find a way to handle the "More" link. I thought about adding a link to More or Show More, but there are posts without that flag. So I'd like to have some way to find out whether an item in the pagination iterator has the more flag or not.

Would that be possible? I can try to update the documentation as well, if someone could point where a note about it would fit better.

Thanks!

**Comment by ludovicchabant** [comment]
Somehow I totally forgot to reply to this? Sorry about that. The post data will have a `has_more` property set to `true` if there was "more" separator.
