### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by Darthen** [ludovicchabant/PieCrust2#30]
Hi,

Using ubuntu 14.04 
the install process returns an error:

distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/bcrypt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yZqnPd-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/bcrypt
Storing debug log for failure in /home/castillo/.pip/pip.log

What can I do? Sorry I'm quite the noob.

**Comment by ludovicchabant** [comment]
It looks like maybe bcrypt didn't install? If you run "pip install bcrypt", what happens?

**Comment by ludovicchabant** [comment]
FYI, I removed the dependency on `bcrypt` since it's only really needed for running FoodTruck on a private server.
