### ISSUE TITLE
"python2" and python3 compatiblity(at the same time)  of Piecrust2 

### ISSUE THREAD

**Issue by zaxebo1** [ludovicchabant/PieCrust2#31]
as at issue https://github.com/ludovicchabant/PieCrust/issues/158#issuecomment-120727076 , you indicated in July 2015, the possibility that Piecrust2 compatibility with python 2.7 will be looked into.

Is there any chance that this was worked upon?   :-)

**Comment by zaxebo1** [comment]
advantage is that:

1) cheap webhosts are still stuck with python 2.6 and some are migrating to 2.7

2) jython (python language implemented in pure java) completely implements python 2.7. 
See http://www.jython.org
So  if Pirecrust2 is ported to python2.7 too, then Piecrust2 flat files CMS  can run on pure JVM(java virtual machine) using jython.

**Comment by ludovicchabant** [comment]
I haven't looked into it, no, and at this point I don't know if I will... it would be time consuming for me, with no real advantages (but other people are free to look into it).

What is your reason for not baking your site before uploading it? If it's a question of convenience of editing/posting, maybe the new publishing features will eventually make it more compelling.
