### ISSUE TITLE
Sass sourcemaps

### ISSUE THREAD

**Issue by sackwort** [ludovicchabant/PieCrust2#33]
Thanks for answering email question regarding getting Sass working; you were right, I hadn't installed it! Sorry about that.

Is it possible to get Sass sourcemaps working?

**Comment by ludovicchabant** [comment]
PieCrust should be generating sourcemaps by default -- it does so in its own cache folder, and uses that for dependency checking when you bake.

If you need to pass custom settings to Sass however you can specify them in your site config. See https://bolt80.com/piecrust/en/latest/docs/reference/asset-processors/
