### ISSUE TITLE
Current entry already exists

### ISSUE THREAD

**Issue by magarciaguerra** [ludovicchabant/PieCrust2#34]
Hello, again :)

I'm having an issue using version 2.0.0rc1 (installed with pip)

When I bake the site I recieve an error that I don't know how to fix it.

```
A current entry already exists for: 8a086d6182...
```

I examine _cache and I don't find that file.
And... wow, when I examine _counter I find months like
5 not 05

So... 'taxonomy pages' and 'assets' can't be proccessed in bake.

Take a look:
[http://zxdevs.com/files/varios/piecrust_issue/issue002.jpg](http://zxdevs.com/files/varios/piecrust_issue/issue002.jpg)

This didn't happen in 2.0.0b5
[http://zxdevs.com/files/varios/piecrust_issue/issue001.jpg](http://zxdevs.com/files/varios/piecrust_issue/issue001.jpg)

Those screenshots are of today bakes (in different computers with different versions of Piecrust)

This is a problem because all internal links (that I made in content) are giving an error or showing out of date pages.

Please, could you help me again, Ludovic?
Thanks a lot :)

**Comment by ludovicchabant** [comment]
Hey! Sorry you're having some trouble... after reviewing the code, it *could* happen if you have 2 tags that you're using in your blog posts that happen to resolve to the same thing after "slugification", _i.e._ after PieCrust processes them so they're in their "URL" form. So for example, 2 tags that only differ in terms of casing, or in terms of a version with accentuated characters and one without... could it be that?

**Comment by ludovicchabant** [comment]
(we figured it out over email IIRC)
