### ISSUE TITLE
Include "wheel" in depenencies

### ISSUE THREAD

**Issue by mboratko** [ludovicchabant/PieCrust2#47]
On a vanilla and updated Debian install, when I create a new venv by default "wheel" is not included. As it turns out, Piecrust does not install properly unless "wheel" is installed. (All packages seem to be installed, but running chef commands results in some dependency conflicts.) In fact, "wheel" has to be installed _first_, and then running `pip install piecrust` works as expected.

**Comment by ludovicchabant** [comment]
Oh interesting, I thought `wheel` was part of the standard Python 3 distribution, since it includes `pip` by default?

What version of `python` and `pip` do you have on Debian?

**Comment by process91** [comment]
Python 3.5.3, pip 9.0.1

**Comment by process91** [comment]
It seems this is not restricted to Debian, nor Python 3.5.3. I ran into the same problem on Python 3.6.1 on Arch Linux.

I think it's related to the way I'm setting up python virtual environments. I'm following [the recommended approach for Python 3](https://docs.python.org/3/library/venv.html). If I create a new virtual env and then install piecrust using pip, it _looks_ like it installs successfully but then "chef" fails with errors. If I instead setup a new virtual env and install wheel using pip first, and then install piecrust, everything works.

**Comment by ludovicchabant** [comment]
6 months later, I finally check back on my Github issues. In the meantime I read up more on Python packaging and started using Pipfile. I just tested with Debian/Python 3.5 and it seems to install the latest version fine, so I'm going to assume I unknowingly fixed it, or one of PieCrust's dependencies fixed themselves.
