### ISSUE TITLE
PieCrust 3.2.1. appears to not make pages correctly

### ISSUE THREAD

**Issue by phosphre** [ludovicchabant/PieCrust2#49]
Hello
* I did a stock install of PieCrust on my mac 10.13.6:
$ pip list | grep -i pie
PieCrust        3.2.1
$ chef --version
chef 3.2.1
$ chef init myblog
$ cd myblog/
$ chef serve
Starting processing loop with output: /Users/mql/Sites/testsite/myblog/_cache/cf1e8c14e54505f60aa10ceb8d5d8ab3/server
[    12.3 ms] setup baker
[     4.9 ms] cache templates
 * Running on http://localhost:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [23/Jul/2018 22:37:22] "GET / HTTP/1.1" 200 -
^C
Shutting server down...

* server serves home page OK
* but then:

$ chef prepare page my-new-page
Creating content: /Users/mql/Sites/testsite/myblog/pages/my-new-page.md
$ chef serve
Starting processing loop with output: /Users/mql/Sites/testsite/myblog/_cache/cf1e8c14e54505f60aa10ceb8d5d8ab3/server
[    12.5 ms] setup baker
[     4.9 ms] cache templates
 \* Running on http://localhost:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [23/Jul/2018 22:37:53] "GET /my-new-page HTTP/1.1" 404 -
127.0.0.1 - - [23/Jul/2018 22:37:58] "GET /my-new-page.html HTTP/1.1" 404 -
127.0.0.1 - - [23/Jul/2018 22:38:05] "GET /pages/my-new-page.html HTTP/1.1" 404 -
127.0.0.1 - - [23/Jul/2018 22:38:09] "GET /pages/my-new-page HTTP/1.1" 404 -

* It says [here](https://bolt80.com/piecrust/en/latest/getting-started/) that if I surf to localhost:8080/my-new-page.html I should see it but no.
$ cd pages
$ cat my-new-page.md
'---'
title: My New Page
time: '22:37:36'
draft: true
'---'

This is a brand new page.

* I'm sure there is an issue, and I hope it's me, but doesn't this look different to what it says in the docs?  I don't want to create a blog, but I do want to use markdown and piecrust cos it looks ace.

**Comment by ludovicchabant** [comment]
I think, noticed the error: the documentation says to go to `localhost:8080/about-me`, not `localhost:8080/about-me.html`.

(I'll add to the TODO list to provide similar available page names in the error message... it would help in this case)

If you want the `.html` extension for your website, you can set `pretty_urls: false` in the config file (see [the config reference](https://bolt80.com/piecrust/en/latest/docs/reference/website-configuration/)).
