### ISSUE TITLE
Problem with page output directory with non-standard site/root

### ISSUE THREAD

**Issue by mrpace2** [ludovicchabant/PieCrust2#5]
I ran into a problem when I tried setting a root URI in config.yml. My piecrust2 sources are located in /var/www/piecrust with baked output going into /var/www/piecrust/_counter.

My Apache server serves the baked website under the http://<server>/piecrust/_counter URL. In order to be able to use `{{ site.root }}` in Jinja, I configured site/root in config.yml: 
```
site:
    root: '/piecrust/_counter/'
```
Unfortunately, this doesn't work. When I bake the site, it prints:
```
# chef bake -f
[     0.9 ms] cleaned cache (reason: ordered to)
[    55.4 ms] [1] /piecrust/_counter/
[    56.4 ms] [0] /piecrust/_counter/test
[    55.4 ms] [2] /piecrust/_counter/test1
[     3.3 ms] [3] assets/css/site.css
[     2.5 ms] [0] assets/js/site.js
```
As you can see, my pages are output into a site.root folder under _counter. Assets are not affected. I hacked around the problem by inserting this code
```python
        # HACK: remove site/root (else page is generated under _counter/site/root)
        if uri.startswith(self.site_root):
            uri = uri[len(self.site_root):]
```
at piecrust/baking/single.py line 113. 

`chef` now outputs the expected page names (test, test1, [main page]), and my pages are generated right in the `_counter` directory.

Can you please take a look into this issue? I'm not sure about any side effects of my dirty hack.

Thanks!

**Comment by ludovicchabant** [comment]
Good find, thanks! Fixed in 50fbf147ce851c41ae70d35ede7c2607544c27bb.
