### ISSUE TITLE
PieCrust admin doesn't work with Flask 1.0

### ISSUE THREAD

**Issue by michaellenaghan** [ludovicchabant/PieCrust2#50]
Here's the error:

    $ chef serve --admin
    Starting processing loop with output: ...
    [    15.8 ms] setup baker
    [     6.1 ms] cache templates
    No module named 'flask.ext'

Here's the problem:

    The following old deprecated code was removed. (#2385)

     * flask.ext - import extensions directly by their name instead of through the flask.ext namespace. For example, import flask.ext.sqlalchemy becomes import flask_sqlalchemy.

That's from the [1.0 changelog](http://flask.pocoo.org/docs/1.0/changelog/#version-1-0).

**Comment by ludovicchabant** [comment]
Fixed in 38401e04d0aff5825f1838052f2abe648f49ee72! Thanks.
