### ISSUE TITLE
bake could not find pagination

### ISSUE THREAD

**Issue by reuben-kagan** [ludovicchabant/PieCrust2#59]
I've just installed piecrust via pip on Arch Linux
initiated some site, have  added some pages and posts, run the chef serve, all works as it should be.
now, chef bake just does not create the static site.
i've tried to find the problem , now my  pages/_index.html looks like this:
<pre>
________________________________________________________________

Visible both for Serve and Bake  
{% if pagination.has_posts %}
<section>
    {% for post in pagination.posts %}
    {% include 'partial_post.html' %}
    {% endfor %}
</section>
<section>
    {% if pagination.prev_page %}<div class="prev"><a href="{{ pagination.prev_page }}">Next Posts</a></div>{% endif %}
    {% if pagination.next_page %}<div class="next"><a href="{{ pagination.next_page }}">Previous Posts</a></div>{% endif %}
</section>
 {% else %}
 
Fall  here if  bake could not find pagination
 
 {% endif %}

_________________________________________________________________________________________________

and the result in _counter/index.html :
______________________________________
  <section id="main" role="main">
        <p>Visible both for Serve and Bake  </p>
        <p>Fall  here if  bake could not find pagination</p>
        
    </section>

when chef serve shows 

 
--
<section id="main" role="main">
  |  
  |  
  |  
  |  
  | <p> Visible both for Serve and Bake  </p>
  |  
  | <section>
  |  
  | <article>
  | <header>
  | <h2><a href="/2020/09/08/second-post">Second Post</a></h2>
  | <small>Sep 08, 2020
  |  
  |  
  | </small>
  | </header>
  | <section>
  | <p>Second Post Test</p>
  | </section>
  | </article>
  |  
  | <article>
  | <header>
  | <h2><a href="/2020/09/08/first-post">First Post</a></h2>
  | <small>Sep 08, 2020
  |  
  |  
  | </small>
  | </header>
  | <section>
  | <p>First Post Test</p>
  | </section>
  | </article>
  |  
  |  
  |  
  | </section>
  |  
</pre>
[test.zip](https://github.com/ludovicchabant/PieCrust2/files/5190012/test.zip)

So the bake could not inizialize pagination , or anything

**Comment by ludovicchabant** [comment]
Ah, that's because both your posts have `draft: true` in their config header.

1. The `chef prepare` command creates posts in draft mode by default so you can publish them when you're ready.
2. The bake process skips draft posts for obvious reasons.
3. The server however shows the draft posts because a local `chef serve` is probably meant to preview work in progress.

I agree it can be a bit confusing or misleading.

**Comment by reuben-kagan** [comment]
Ah, Thanks a lot! 
I would say, the best suggestion would be to put it in documentation just where the bake command is first mentioned.probably, with a warning.
