### ISSUE TITLE
Categories, tags pages jinja2.exceptions.UndefinedError

### ISSUE THREAD

**Issue by zimmicz** [ludovicchabant/PieCrust2#6]
I used to have categories (similar for tags) page with v1 defined as follows:

categories.html

```
---
title: Categories
description: Categories
layout: page
format: none
---
<ul>
	{% for c in blog.categories %}
		<li><a href="{{pccaturl(c.name)}}">{{c.name}}</a></li>
	{% endfor %}
</ul>
```

_category.html

```
---
format: none
---
<section>
{% for post in pagination.posts %}
		{% include 'partial_post.html' %}
{% endfor %}
</section>
```

The same layout gives me an error with v2:
```
jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: 'blog' is undefined
```

How do I list categories (and tags) with v2? I looked into debug_info and didn't find anything related to this.

**Comment by ludovicchabant** [comment]
Indeed. Fixed with e62d2ca3614470e577779692973e75389cae3aed.
Thanks a lot for reporting this!
(and yeah, debug_info is not quite there yet, stuff is not formatted or reported correctly... it's still a work in progress :) )
