### ISSUE TITLE
TypeError: %d format: a number is required, not NoneType

### ISSUE THREAD

**Issue by zimmicz** [ludovicchabant/PieCrust2#7]
I've been using `post_url: '%year%/%slug%'` config for posts URLs with v1. When visiting such an URL with v2, it gives the following error:

![screenshot from 2015-03-28 13 37 35](https://cloud.githubusercontent.com/assets/6543598/6881065/1442b27c-d550-11e4-9825-6b46fa28bb2d.png)

I guess Piecrust wants me to provide valid %month%, but I don't want to use it. I use flat hierarchy so every post is located inside posts directory with no nested subdirectories.

**Comment by ludovicchabant** [comment]
This seems to work fine with the latest. I believe this was fixed a while ago with fd16213bd0110ebfae402433821640fc7376a441. Did you install from `pip` or directly from Git repo?

**Comment by zimmicz** [comment]
@ludovicchabant pip, I'll try with git.

**Comment by zimmicz** [comment]
Fixed with latest git.

**Comment by ludovicchabant** [comment]
Thanks for checking! The `pip` package is quite outdated since I wanted to update it only after I had a first documentation draft written (which is almost done).
