### ISSUE TITLE
werkzeug.exceptions.NotFound for single category page

### ISSUE THREAD

**Issue by zimmicz** [ludovicchabant/PieCrust2#8]
I try to access posts listing for one of categories with the latest git version. It works fine with tags, but fails with category.
![screenshot from 2015-03-29 13 00 06](https://cloud.githubusercontent.com/assets/6543598/6885172/8a7bb876-d613-11e4-8985-88fa5041139f.png)

categories.html looks like this:

```
---
title: Categories
description: Categories
layout: page
format: none
---
<ul>
	{% for c in blog.categories %}
		<li><a href="{{pccaturl(c.name)}}">{{c.name}}</a></li>
	{% endfor %}
</ul>
```

_category.html looks like this:

```
---
format: none
---
<section>
{% for post in pagination.posts %}
		{% include 'partial_post.html' %}
{% endfor %}
</section>
```

**Comment by ludovicchabant** [comment]
Fixed with b7bae9f5445063e9bba9f04cdfdd872167f9f12f. Thanks for reporting again! :)
