### ISSUE TITLE
RSS feed date format error

### ISSUE THREAD

**Issue by zimmicz** [ludovicchabant/PieCrust2#9]
Using

```
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
<channel>
	<title>{{site.title}}</title>
	<link>http://zimmi.cz/posts</link>
	<lastBuildDate>{{now|date('r')}}</lastBuildDate>
	<pubDate>{{now|date('r')}}</pubDate>
	<description>{{site.description}}</description>
	{% for post in blog.posts.limit(10) %}
	<item>
		<title>{{ post.title }}</title>
		<link>http://zimmi.cz{{ post.url }}</link>
		<pubDate>{{ post.timestamp|date('r') }}</pubDate>
		<guid>http://zimmi.cz{{post.url}}</guid>
		<description>{{ post.content }}</description>
	</item>
	{% endfor %}
</channel>
</rss>
```

results in

```
PieCrust 1 date formats won't work in PieCrust 2. You probably want a format that look like 'r'. Please check the `strftime` formatting page here: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior
```
However, there is no filter named `strptime` nor `strftime` in v2. How do I format the date then?

**Comment by ludovicchabant** [comment]
Yeah the message is maybe misleading... what it's saying is that the *string formats* are different between PHP and Python, but the `|date()` filter is still valid. It's the string you pass to `|date()` that changes.

So you pass `'r'` (a valid [PHP date format](http://php.net/manual/en/function.date.php)), but you need to pass something else (a valid [Python date format](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior), which is what the error message is pointing you to).

I just added an `emaildate()` function to the Jinja environment so you can use that, but I haven't pushed it to Github yet (only to Bitbucket). I'll do that tonight. This makes it easier than trying to reconstruct an RFC2822 date using Python date formatter tokens.

**Comment by ludovicchabant** [comment]
Pushed! Fixed with f14f7be3c091382a57d22a6c8c130cd969a078a1.

**Comment by zimmicz** [comment]
@ludovicchabant it seems `<lastBuildDate>{{now|date('%a, %d %b %Y %H:%M:%S %z')}}</lastBuildDate>` is causing the trouble as `now` became undefined.

**Comment by ludovicchabant** [comment]
Ah interesting, I'll add an actual `now` object to the Jinja context to increase backward compatibility.
